# Generated by Django 5.0.6 on 2024-06-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orienteering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
