# Generated by Django 5.0.6 on 2024-06-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orienteering', '0003_remove_checkpointrecord_checkpoint_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='racerunner',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
