# Generated by Django 5.0.6 on 2024-06-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orienteering', '0003_alter_racetype_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='racerunner',
            name='checkpoint_record',
            field=models.ManyToManyField(blank=True, null=True, related_name='race_runner_checkpoints', to='orienteering.checkpoint'),
        ),
    ]
