# Generated by Django 5.0.6 on 2024-06-18 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orienteering', '0004_racerunner_checkpoint_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racerunner',
            name='checkpoint_record',
        ),
        migrations.CreateModel(
            name='CheckPointRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('checkpoint_id', models.IntegerField()),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('race_runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_records', to='orienteering.racerunner')),
            ],
        ),
    ]
