# Generated by Django 5.0.6 on 2024-06-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orienteering', '0004_alter_checkpoint_score_alter_racerunner_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racerunner',
            name='total_time',
            field=models.DurationField(blank=True, default=0, null=True),
        ),
    ]
