# Generated by Django 5.0.6 on 2024-06-18 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orienteering', '0005_remove_racerunner_checkpoint_record_checkpointrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointrecord',
            name='race_runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_recordsRa', to='orienteering.racerunner'),
        ),
    ]
