# Generated by Django 5.0.6 on 2024-06-18 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orienteering', '0006_alter_checkpointrecord_race_runner'),
    ]

    operations = [
        migrations.AddField(
            model_name='racerunner',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkpointrecord',
            name='race_runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_records', to='orienteering.racerunner'),
        ),
    ]
