# Generated by Django 5.0.6 on 2024-06-18 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orienteering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprunner',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_group_runners', to=settings.AUTH_USER_MODEL),
        ),
    ]
