# Generated by Django 5.0.6 on 2024-06-17 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('orienteering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_group', to='auth.group'),
        ),
    ]
